"""Document data structures used by ChordPages."""

from chordpages.document.chordpro import (
    BlankLine,
    ChordLyricLine,
    ChordProDirective,
    ChordProSong,
    ChordToken,
    LyricSyllable,
    SongSection,
    SongSectionKind,
    build_lyric_syllables,
    build_song_sections,
    parse_chordpro,
    render_chord_line,
    render_chord_over_lyrics,
    wrap_chord_lyric_line,
)
from chordpages.document.dom import (
    DocumentBlock,
    DocumentDom,
    ParagraphBlock,
    SongBlock,
)
from chordpages.document.layout import ChordProLayout, RenderRow, layout_chordpro_song
from chordpages.document.model import ChordPagesDocument
from chordpages.document.pagination import (
    PaginatedLayout,
    RenderColumn,
    RenderPage,
    paginate_layout,
)
from chordpages.document.page import (
    CHORDPAGES_PAGE_SIZE,
    CUSTOM_PAGE_SIZE,
    DEFAULT_PAGE_MARGINS,
    DEFAULT_PAGE_SIZE,
    DEFAULT_TEXT_LINE_HEIGHT_MM,
    MARGIN_PRESETS_MM,
    MarginPresetName,
    PageLayout,
    PageMargins,
    margin_preset_names,
    page_size_names,
)
from chordpages.document.songbook import ChordPagesSongbook
from chordpages.document.structure import DocumentModel, DocumentPage
from chordpages.document.text_file import (
    TextFileInfo,
    detect_file_type,
    detect_newline,
    normalize_newlines,
    read_text_file,
    restore_newlines,
    write_text_file,
)
from chordpages.document.transpose import transpose_chord, transpose_note, transpose_text

__all__ = [
    "BlankLine",
    "ChordLyricLine",
    "ChordProDirective",
    "ChordProLayout",
    "ChordProSong",
    "ChordToken",
    "CHORDPAGES_PAGE_SIZE",
    "CUSTOM_PAGE_SIZE",
    "DEFAULT_PAGE_MARGINS",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_TEXT_LINE_HEIGHT_MM",
    "DocumentBlock",
    "DocumentDom",
    "DocumentModel",
    "DocumentPage",
    "ChordPagesDocument",
    "ChordPagesSongbook",
    "MARGIN_PRESETS_MM",
    "MarginPresetName",
    "ParagraphBlock",
    "PaginatedLayout",
    "PageLayout",
    "PageMargins",
    "RenderColumn",
    "RenderPage",
    "RenderRow",
    "LyricSyllable",
    "SongBlock",
    "SongSection",
    "SongSectionKind",
    "TextFileInfo",
    "build_lyric_syllables",
    "build_song_sections",
    "detect_file_type",
    "detect_newline",
    "layout_chordpro_song",
    "margin_preset_names",
    "normalize_newlines",
    "page_size_names",
    "paginate_layout",
    "parse_chordpro",
    "read_text_file",
    "render_chord_line",
    "render_chord_over_lyrics",
    "restore_newlines",
    "transpose_chord",
    "transpose_note",
    "transpose_text",
    "write_text_file",
    "wrap_chord_lyric_line",
]
